try {
  // some code that might throw an error
} catch (error: any) {
  // now you can use 'error' variable here
}
